version: "3.8"
services:
  uoh-file-browser:
    image: uoh-fb
    ports:
      - "6942:3000"
    volumes:
      - ./local.db:/local.db
      - /media/odilf/:/files/
    build: ./

networks:
  uoh-fb-network:
